# Generated by Django 5.2.3 on 2025-07-01 06:23

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên đại lý')),
            ],
            options={
                'verbose_name': 'Đại lý',
                'verbose_name_plural': '1. Danh sách đại lý',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên dự án')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('key_prefixes', models.JSONField(blank=True, default=list, verbose_name='Các tiền tố của mã căn hộ')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': '2. Danh sách Dự án',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('level', models.CharField(max_length=50, verbose_name='Cấp độ')),
                ('message', models.TextField(verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Log của Worker',
                'verbose_name_plural': '7. Log của Worker',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gid', models.CharField(blank=True, max_length=100)),
                ('html_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('header_row_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dòng header (số)')),
                ('invalid_colors', models.JSONField(blank=True, default=management.models.get_default_invalid_colors, verbose_name='Các màu không hợp lệ')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.agent', verbose_name='Đại lý')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Cấu hình Dự án',
                'verbose_name_plural': '3. Cấu hình các Dự án',
            },
        ),
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('change_type', models.CharField(choices=[('added', 'Thêm mới'), ('removed', 'Đã bán'), ('changed', 'Thay đổi')], max_length=10, verbose_name='Loại thay đổi')),
                ('apartment_key', models.CharField(max_length=100, verbose_name='Mã căn hộ')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='Chi tiết')),
                ('project_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.projectconfig', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Lịch sử thay đổi',
                'verbose_name_plural': '5. Lịch sử Thay đổi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('data', models.TextField(verbose_name='Bản ghi quỹ căn hộ')),
                ('project_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.projectconfig', verbose_name='Nguồn dữ liệu dự án')),
            ],
            options={
                'verbose_name': 'Bản ghi quỹ căn hộ',
                'verbose_name_plural': '6. Danh sách Bản ghi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(help_text="Tên dùng trong code, ví dụ: 'key', 'price'. Viết liền, không dấu.", max_length=50, verbose_name='Tên nội bộ')),
                ('display_name', models.CharField(help_text='Tên sẽ hiển thị trong các thông báo.', max_length=100, verbose_name='Tên hiển thị')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Danh sách các tên tiêu đề trong file nguồn.', verbose_name='Các tên tiêu đề có thể có')),
                ('is_identifier', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là cột mã định danh.', verbose_name='Là cột định danh?')),
                ('project_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='management.projectconfig', verbose_name='Cấu hình Dự án')),
            ],
            options={
                'verbose_name': 'Ánh xạ cột',
                'verbose_name_plural': 'Ánh xạ các Cột',
                'unique_together': {('project_config', 'internal_name')},
            },
        ),
    ]
