# Generated by Django 5.2.3 on 2025-07-15 18:04

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên đại lý')),
            ],
            options={
                'verbose_name': 'Đại lý',
                'verbose_name_plural': 'Danh sách đại lý',
            },
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Tên dự án')),
                ('spreadsheet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gid', models.CharField(max_length=100)),
                ('html_url', models.URLField(blank=True, max_length=500, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('header_row_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dòng header (số)')),
                ('key_prefixes', models.JSONField(default=list, verbose_name='Các tiền tố của mã căn hộ')),
                ('invalid_colors', models.JSONField(blank=True, default=management.models.get_default_invalid_colors, verbose_name='Các màu không hợp lệ')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.agent', verbose_name='Đại lý')),
            ],
            options={
                'verbose_name': 'Đại lý & Dự án',
                'verbose_name_plural': 'Danh sách các dự án',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('data', models.TextField(verbose_name='Bản ghi quỹ căn hộ')),
                ('project_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.projectconfig', verbose_name='Đại lý & Dự án')),
            ],
            options={
                'verbose_name': 'Bản ghi quỹ căn hộ',
                'verbose_name_plural': 'Danh sách bản ghi quỹ căn hộ',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(help_text="Tên dùng trong code, ví dụ: 'key', 'price', 'policy'. Viết liền, không dấu.", max_length=50, verbose_name='Tên')),
                ('display_name', models.CharField(help_text='Tên sẽ hiển thị trong các thông báo.', max_length=100, verbose_name='Mô tả')),
                ('aliases', models.JSONField(default=list, help_text='Danh sách các tên tiêu đề trong file nguồn, dạng JSON list.', verbose_name='Các tên tiêu đề có thể có')),
                ('is_identifier', models.BooleanField(default=False, help_text='Tích vào đây nếu đây là cột chứa mã định danh duy nhất (ví dụ: Mã căn hộ).', verbose_name='Là cột định danh?')),
                ('project_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='management.projectconfig', verbose_name='Cấu hình Dự án')),
            ],
            options={
                'verbose_name': 'Ánh xạ Tiêu đề',
                'verbose_name_plural': 'Các ánh xạ Tiêu đề',
                'unique_together': {('project_config', 'internal_name')},
            },
        ),
    ]
