# Generated by Django 5.2.3 on 2025-06-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên đại lý')),
            ],
            options={
                'verbose_name': 'Đại lý',
                'verbose_name_plural': 'Các Đại lý',
            },
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Tên dự án')),
                ('spreadsheet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gid', models.CharField(max_length=100)),
                ('html_url', models.URLField(blank=True, max_length=500, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('header_row_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dòng header (số)')),
                ('key_column_aliases', models.JSONField(blank=True, default=list, verbose_name='Các tên cột Key')),
                ('price_column_aliases', models.JSONField(blank=True, default=list, verbose_name='Các tên cột Giá')),
                ('key_prefixes', models.JSONField(blank=True, default=list, verbose_name='Các tiền tố của Key')),
                ('invalid_colors', models.JSONField(blank=True, default=list, verbose_name='Các màu không hợp lệ')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.agent', verbose_name='Đại lý')),
            ],
            options={
                'verbose_name': 'Cấu hình Dự án',
                'verbose_name_plural': 'Các Cấu hình Dự án',
            },
        ),
    ]
