# Generated by Django 5.2.3 on 2025-06-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('data', models.TextField(verbose_name='Dữ liệu snapshot')),
                ('project_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.projectconfig', verbose_name='Đại lý & Dự án')),
            ],
            options={
                'verbose_name': 'Bản ghi',
                'verbose_name_plural': 'Bản ghi quỹ căn hộ',
                'ordering': ['-timestamp'],
            },
        ),
    ]
