# Generated by Django 5.2.3 on 2025-07-01 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(help_text='Mã định danh của căn hộ.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_config', models.ForeignKey(help_text='Cấu hình dự án chứa căn hộ này.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='management.projectconfig')),
            ],
            options={
                'verbose_name': 'Quỹ Căn Hộ',
                'verbose_name_plural': '4. Danh sách quỹ căn',
                'unique_together': {('project_config', 'unit_code')},
            },
        ),
    ]
