# Generated by Django 5.2.3 on 2025-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_apartmentunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentunit',
            name='sales_policy',
            field=models.TextField(blank=True, help_text='Chính sách bán hàng áp dụng cho riêng căn hộ này.', null=True),
        ),
    ]
