# Generated by Django 5.2.3 on 2025-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên tác vụ')),
                ('task', models.CharField(help_text='Đường dẫn đến script, ví dụ: worker/run.sh', max_length=255, verbose_name='Script')),
                ('cron_schedule', models.CharField(help_text="Định dạng Crontab, ví dụ: '*/5 * * * *' để chạy mỗi 5 phút", max_length=100, verbose_name='Lịch chạy (Cron)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Lần chạy cuối')),
            ],
            options={
                'verbose_name': 'Tác vụ định kỳ',
                'verbose_name_plural': 'Danh sách tác vụ định kỳ',
            },
        ),
    ]
