# Generated by Django 5.2.3 on 2025-07-03 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_apartmentunit_sales_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Token cho bot Telegram để gửi thông báo.', max_length=255, null=True, verbose_name='Telegram Bot Token')),
                ('proxy_url', models.CharField(blank=True, help_text='URL proxy để các worker sử dụng cho request, ví dụ: http://user:pass@host:port', max_length=255, null=True, verbose_name='URL Proxy')),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': '0. Cấu hình hệ thống',
            },
        ),
        migrations.AlterModelOptions(
            name='inventorychange',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lịch sử thay đổi', 'verbose_name_plural': '5. Lịch sử thay đổi'},
        ),
        migrations.AlterField(
            model_name='apartmentunit',
            name='sales_policy',
            field=models.TextField(blank=True, help_text='Chính sách bán hàng áp dụng cho riêng căn hộ này.', null=True, verbose_name='CSBH'),
        ),
        migrations.AlterField(
            model_name='apartmentunit',
            name='unit_code',
            field=models.CharField(help_text='Mã định danh của căn hộ.', max_length=255, verbose_name='Mã căn hộ'),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='apartment_key',
            field=models.CharField(max_length=255, verbose_name='Mã căn hộ'),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Chi tiết'),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm'),
        ),
    ]
