# Generated by Django 5.2.3 on 2025-06-19 00:33

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_scheduledtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='key_column_aliases',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='price_column_aliases',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Định nghĩa các cột cần lấy dữ liệu và các tên có thể có của chúng.', verbose_name='Cấu hình các cột tùy chỉnh'),
        ),
        migrations.AlterField(
            model_name='projectconfig',
            name='invalid_colors',
            field=models.JSONField(blank=True, default=management.models.get_default_invalid_colors, verbose_name='Các màu không hợp lệ'),
        ),
    ]
