# Generated by Django 5.2.3 on 2025-06-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_projectconfig_key_column_aliases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='column_mapping',
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(help_text="Tên dùng trong code, ví dụ: 'key', 'price', 'policy'. Viết liền, không dấu.", max_length=50, verbose_name='Tên nội bộ')),
                ('display_name', models.CharField(help_text='Tên sẽ hiển thị trong các thông báo.', max_length=100, verbose_name='Tên hiển thị')),
                ('aliases', models.JSONField(default=list, help_text='Danh sách các tên cột trong file nguồn, dạng JSON list.', verbose_name='Các tên cột có thể có')),
                ('is_identifier', models.BooleanField(default=False, help_text='Tích vào đây nếu đây là cột chứa mã định danh duy nhất (ví dụ: Mã căn hộ).', verbose_name='Là cột định danh?')),
                ('project_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='management.projectconfig', verbose_name='Cấu hình Dự án')),
            ],
            options={
                'verbose_name': 'Ánh xạ Cột',
                'verbose_name_plural': 'Các Ánh xạ Cột',
                'unique_together': {('project_config', 'internal_name')},
            },
        ),
    ]
