# Generated by Django 5.2.3 on 2025-06-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_projectconfig_column_mapping_columnmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfig',
            name='key_prefixes',
            field=models.JSONField(default=list, verbose_name='Các tiền tố của Key'),
        ),
    ]
