# Generated by Django 5.2.3 on 2025-06-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_projectconfig_key_prefixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnmapping',
            options={'verbose_name': 'Ánh xạ Tiêu đề', 'verbose_name_plural': 'Các ánh xạ Tiêu đề'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Bản ghi quỹ căn hộ', 'verbose_name_plural': 'Danh sách bản ghi quỹ căn hộ'},
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='aliases',
            field=models.JSONField(default=list, help_text='Danh sách các tên tiêu đề trong file nguồn, dạng JSON list.', verbose_name='Các tên tiêu đề có thể có'),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='display_name',
            field=models.CharField(help_text='Tên sẽ hiển thị trong các thông báo.', max_length=100, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='internal_name',
            field=models.CharField(help_text="Tên dùng trong code, ví dụ: 'key', 'price', 'policy'. Viết liền, không dấu.", max_length=50, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='projectconfig',
            name='key_prefixes',
            field=models.JSONField(default=list, verbose_name='Các tiền tố của mã căn hộ'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task',
            field=models.CharField(help_text='Đường dẫn đến script, ví dụ: worker/run.sh', max_length=255, verbose_name='Đường dẫn Script'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='data',
            field=models.TextField(verbose_name='Bản ghi quỹ căn hộ'),
        ),
    ]
