# Generated by Django 5.2.3 on 2025-06-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_columnmapping_options_alter_snapshot_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
    ]
