services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=your_strong_password
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"

  app:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=inventory_db
      - DB_USER=inventory_user
      - DB_PASS=your_strong_password
    depends_on:
      - db
      - redis

  celery-worker:
    build: .
    command: celery -A configuration worker -l info
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=inventory_db
      - DB_USER=inventory_user
      - DB_PASS=your_strong_password
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A configuration beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
